from smarttvleakage.utils.constants import KeyboardType


# Samsung Smart TV Sounds
SAMSUNG_DELETE = 'delete'
SAMSUNG_DOUBLE_MOVE = 'double_move'
SAMSUNG_KEY_SELECT = 'key_select'
SAMSUNG_MOVE = 'move'
SAMSUNG_SELECT = 'select'


# Apple TV Sounds
APPLETV_KEYBOARD_DELETE = 'keyboard_delete'
APPLETV_KEYBOARD_MOVE = 'keyboard_move'
APPLETV_KEYBOARD_DOUBLE_MOVE = 'keyboard_double_move'
APPLETV_KEYBOARD_SCROLL_DOUBLE = 'keyboard_scroll_double'
APPLETV_KEYBOARD_SCROLL_TRIPLE = 'keyboard_scroll_triple'
APPLETV_KEYBOARD_SCROLL_FOUR = 'keyboard_scroll_four'
APPLETV_KEYBOARD_SCROLL_FIVE = 'keyboard_scroll_five'
APPLETV_KEYBOARD_SCROLL_SIX = 'keyboard_scroll_six'
APPLETV_KEYBOARD_SELECT = 'keyboard_select'
APPLETV_SYSTEM_MOVE = 'system_move'
APPLETV_TOOLBAR_MOVE = 'toolbar_move'


# Collect all sounds for each system
#SAMSUNG_SOUNDS = frozenset([SAMSUNG_DOUBLE_MOVE, SAMSUNG_KEY_SELECT, SAMSUNG_MOVE, SAMSUNG_SELECT, SAMSUNG_DELETE])
SAMSUNG_SOUNDS = frozenset([SAMSUNG_KEY_SELECT, SAMSUNG_MOVE, SAMSUNG_SELECT, SAMSUNG_DELETE])
APPLETV_SOUNDS = frozenset([APPLETV_KEYBOARD_MOVE, APPLETV_KEYBOARD_SELECT, APPLETV_KEYBOARD_DELETE, APPLETV_TOOLBAR_MOVE])
APPLETV_SOUNDS_EXTENDED = frozenset([APPLETV_KEYBOARD_MOVE, APPLETV_KEYBOARD_SELECT, APPLETV_KEYBOARD_DELETE, APPLETV_TOOLBAR_MOVE, APPLETV_KEYBOARD_SCROLL_DOUBLE, APPLETV_KEYBOARD_SCROLL_TRIPLE, APPLETV_KEYBOARD_SCROLL_FOUR, APPLETV_KEYBOARD_SCROLL_FIVE])

APPLETV_MOVE_SOUNDS = frozenset([APPLETV_KEYBOARD_MOVE, APPLETV_KEYBOARD_SCROLL_DOUBLE, APPLETV_KEYBOARD_SCROLL_TRIPLE, APPLETV_KEYBOARD_SCROLL_FOUR, APPLETV_KEYBOARD_SCROLL_FIVE, APPLETV_KEYBOARD_SCROLL_SIX])

# Dictionary to map move sounds to the actual number of moves they incur
APPLETV_MOVE_COUNTS = {
    APPLETV_KEYBOARD_MOVE: 1,
    APPLETV_KEYBOARD_SCROLL_DOUBLE: 2,
    APPLETV_KEYBOARD_SCROLL_TRIPLE: 3,
    APPLETV_KEYBOARD_SCROLL_FOUR: 4,
    APPLETV_KEYBOARD_SCROLL_FIVE: 5,
    APPLETV_KEYBOARD_SCROLL_SIX: 6
}


# Make a dictionary for the sounds made on certain `special` keys
DONE_SOUNDS = {
    KeyboardType.SAMSUNG: SAMSUNG_SELECT,
    KeyboardType.APPLE_TV_PASSWORD: APPLETV_TOOLBAR_MOVE,
    KeyboardType.APPLE_TV_SEARCH: APPLETV_SYSTEM_MOVE
}


SPACE_SOUNDS = {
    KeyboardType.SAMSUNG: SAMSUNG_SELECT,
    KeyboardType.APPLE_TV_PASSWORD: APPLETV_KEYBOARD_SELECT,
    KeyboardType.APPLE_TV_SEARCH: APPLETV_KEYBOARD_SELECT
}


CHANGE_SOUNDS = {
    KeyboardType.SAMSUNG: SAMSUNG_SELECT,
    KeyboardType.APPLE_TV_PASSWORD: APPLETV_KEYBOARD_SELECT,
    KeyboardType.APPLE_TV_SEARCH: APPLETV_KEYBOARD_SELECT
}


KEY_SELECT_SOUNDS = {
    KeyboardType.SAMSUNG: SAMSUNG_KEY_SELECT,
    KeyboardType.APPLE_TV_PASSWORD: APPLETV_KEYBOARD_SELECT,
    KeyboardType.APPLE_TV_SEARCH: APPLETV_KEYBOARD_SELECT
}
